### PR TITLE
Bump Ruby 2.4, Compass -> Sass

### PR DESCRIPTION
**Pull request by davious**
This change is [Reviewable](https://reviewable.io/reviews/ncarb/heroku-buildpack-nodejs-grunt-compass/3)

### CODE REVIEW

**Comment by ESimmonds** [comment]
that ruby path needs a latest folder, will rear it's ugly head in the next version. good fix, I'm sure this was such a pain.

**Comment by davious** [comment]
tnx. I'm betting there is a better fix even though this gets it working

**Comment by ESimmonds** [comment]
feeling my way through it, connected reviewable to the repo

**Comment by ESimmonds** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ncarb/heroku-buildpack-nodejs-grunt-compass/3)*

**Comment by davious** [comment]
btw.. that reviewable is not my doing. I'm not a fan of it myself.

**Comment by ESimmonds** [comment]
was a little trippy, options were to squash and merge or rebase fast forward without a delete. All works out

**Pull request merged**
